name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Instalar dependencias
      run: npm install

    - name: Verificar aplicación
      run: node server.js &

    - name: Construir imagen Docker
      run: docker build -t devops-app .
